### ISSUE TITLE
How does this compare with the Aliyun Java API?

### ISSUE THREAD

**Issue by PhilAndrew** [fit2cloud/aliyun-api-java-wrapper#1]
What is the difference between this and the Aliyun Java API?

Why would I want to use this?

The Aliyun Java API is here.
https://github.com/aliyun/aliyun-openapi-java-sdk

Thanks, Philip

**Comment by fit2cloud** [comment]
Hi Philip,

Aliyun offiical Java SDK is a better choice for you.  We created this project two years ago. At that time, Aliyun didn't release offical Java SDK. 

Thanks,
Zhimin
